### ISSUE TITLE
No eligible build target

### ISSUE THREAD

**Issue by janosimas** [siegelaaron94/atom-build-cmake#1]
I create a build forlder in ${CMAKE_SOURCE_DIR}/build
and executed the cmake to generate tha config files.

when I try to run atom-build, I get: "No eligible build target"

**Comment by siegelaaron94** [comment]
I did not think of cmake project structures like terrama2 where they put the main CMakeLists.txt file in some folder other than the root of the project. They make it even worse by calling it build, I will fix this my moving to a real out of source build where the build directory is called ${project_name}-build.

**Comment by janosimas** [comment]
Great news :+1: 

thanks for the fast answer. :-)
