### ISSUE TITLE
Retrieve targets for Ninja generator

### ISSUE THREAD

**Issue by neumannrf** [siegelaaron94/atom-build-cmake#11]
I miss the feature that lists all the targets upon pressing `ctrl+alt+t` when I am using Ninja as generator. I tried to implement a similar feature in my local `~/.atom/packages/build-cmake/lib/cmake.js` file but failed.

I simply created new functions

``` Javascript
        createNinjaTarget(target_name) {
            return {
                atomCommandName : 'cmake:' + target_name,
                name : target_name,
                exec : this.executable,
                cwd : this.source_dir,
                args : ['--build', this.build_dir, '--target',target_name,'--'],
                errorMatch : compileErrorMatch.concat(generateErrorMatch),
                warningMatch : compileWarningMatch.concat(generateWarningMatch),
                sh : false
            };
        }
```

and

``` Javascript
        ninjaTargets() {
            output = execSync(
              this.executable + ' --build ' + this.build_dir + ' --target help', { cwd: this.build_dir });
            return output.toString('utf8')
            .split(/[\r\n]{1,2}/)
            .filter(line => line.startsWith('...'))
            .map((line) => this.createNinjaTarget(line.replace('... ','').split(' ')[0]));
        }
```

and, finally, added the conditional for the generator at the end of the file like

``` Javascript
                else if(generator.match('Ninja'))
                    return [ generateTarget ].concat(this.ninjaTargets());
```

Is there something missing? Is it at all **possible** to do with Ninja the same as with GNU Make?

**Comment by siegelaaron94** [comment]
I added support in version 0.6.0 for Ninja as a response to this. Your issue is with this block of code

``` Javascript
        ninjaTargets() {
            output = execSync(
              this.executable + ' --build ' + this.build_dir + ' --target help', { cwd: this.build_dir });
            return output.toString('utf8')
            .split(/[\r\n]{1,2}/)
            .filter(line => line.startsWith('...'))
            .map((line) => this.createNinjaTarget(line.replace('... ','').split(' ')[0]));
        }
```

This parsing the output from Make and Ninja's output is different.

**Comment by neumannrf** [comment]
Wow, that was fast! Thank you!

**Comment by neumannrf** [comment]
@siegelaaron94 When I choose `Ninja` as generator from the drop-down menu, the retrieval of targets is severely affected. The `clean` target, for instance, is missing. As is every custom target defined in my `CMakeLists.txt`. It used to work well previously...

PS: I am running `Atom 1.14.3` on macOS Sierra with `build v0.67.0` and `build-cmake v0.8.3`.
