### ISSUE TITLE
Build location not working

### ISSUE THREAD

**Issue by janosimas** [siegelaaron94/atom-build-cmake#26]
The tag PROJECT_DIR is not working,
building in a folder with the same name as the source dir but with '-build' after is doesn't work.

I was expecting to have I look on it but couldn't find the time.

**Comment by siegelaaron94** [comment]
I am not sure why it would not be working. '$PROJECT_DIR-build' works for me on Windows and Linux with version 0.8.3.

**Comment by janosimas** [comment]
Weird

Is there any debugging flag so I can see the expansion?

**Comment by siegelaaron94** [comment]
Did you ever resolve this? There are not any ways to debug this without just putting print statements everywhere.

**Comment by janosimas** [comment]
no :-/

well, there could be a flag in the config that enabled lots of debugging "if" :-D

**Comment by siegelaaron94** [comment]
What does your full path to your project look like? Does it have spaces, $, or any other weird characters?

**Comment by janosimas** [comment]
just a common path, the weirdest character is a "-"
/home/username/MyDevel/project
/home/username/MyDevel/project-build

**Comment by janosimas** [comment]
I think I found it,
it the `cmake.js` you set `this.source_dir` as the `source_dir + cmakelists`
so when `pathVars` is read it's not just the "atom project dir", it's the "cmake project dir"

in my case I have my project dir:
`.../devel/project`
my cmake dir:
`.../devel/project/build/cmake`
my build dir:
`.../devel/project-build`

the way it's working the cmake build creates the dir:
`.../devel/project/build/cmake-build`

**Comment by siegelaaron94** [comment]
Perfect that is the information that I needed, thanks it should be fixed in 0.9.1.
