### ISSUE TITLE
Build does not work in Fedora 25

### ISSUE THREAD

**Issue by alex94cp** [siegelaaron94/atom-build-cmake#30]
When invoking the *generate* target from a CMake project, there appears a lot of BASH_FUNC_module and BASH_FUNC_scl errors (exactly same errors as [here](https://github.com/atom/atom/issues/13451) and [here](https://github.com/platformio/platformio-atom-ide-terminal/issues/120)), whenever atom is launched from /usr/share/atom/atom (from GNOME Panel). However, build works when atom is launched from /usr/bin/atom (when launched from a terminal).

It seems other packages are having [similar issues](https://github.com/platformio/platformio-atom-ide-terminal/issues/120). At first I thought it had to do with [Wayland not processing .bash_profile/.bashrc](https://fedoraproject.org/wiki/Common_F25_bugs#gnome-login-shell), however [that seems to have been fixed already](https://admin.fedoraproject.org/updates/FEDORA-2017-84b0233854). Also, I tried triggering a build from a GNOME Xorg session and still found the same issue.

My atom version is 1.17 and I'm running Fedora 25.

**Comment by siegelaaron94** [comment]
Thanks,

I have had issues with this same problem before and I could not solve the issue, I will give another go at it when I have some spare time to spin up a Fedora Image. This problem seams to be Fedora related as every thing works on Ubuntu 16.10 and Arch.

**Comment by siegelaaron94** [comment]
~~[Here](https://gist.github.com/siegelaaron94/79ca409eb73eec164fe4676b6e6e159f) is a basic atom package that reproduces the bug if you feel like submitting the issue on the atom project.~~ Nevermind this does not reproduce the problem, I am not sure what is going on then.

**Comment by ashcrow** [comment]
@siegelaaron94 possible fix at https://github.com/atom/atom/pull/15887
