### ISSUE TITLE
No function

### ISSUE THREAD

**Issue by Moerten** [siegelaaron94/atom-build-cmake#34]
I installed the addon, but nothing happened. No StatusBar Buttons/Icons are visible nor i could find a new menu entry for cmake. Pressing F5 and F7 also had no action. Did i miss something?

**Comment by siegelaaron94** [comment]
Have you installed the [build](https://atom.io/packages/build) plugin?

**Comment by Moerten** [comment]
Thanks for your fast reply and no I haven't :). Maybe that should be noted somewhere as an dependency. I'll try it again this evening.

**Comment by siegelaaron94** [comment]
That should fix the issue, and yes the dependency on build should be noted.
