### ISSUE TITLE
Can't figure out what I'm doing wrong.

### ISSUE THREAD

**Issue by ricanteja** [siegelaaron94/atom-build-cmake#35]
I installed Build and Build-CMake but I can't build anything.

Here is my cmake file
```cmake
cmake_minimum_required(VERSION 3.0)

set(CMAKE_BUILD_TYPE Debug)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

project(example)

add_executable(
    sample
    header.hpp
    main.cpp
)
```
Its in the same directory as the source files. The Build-CMake package is configured to look for CMake files in the root directory. I press F9 and it says "No configuration to build this project exists."

Any help appreciated. Thanks!

**Comment by siegelaaron94** [comment]
What did you call the cmake make file? It should be called CMakeLists.txt, and the CMakeLists path should be blank in the settings.

**Comment by ricanteja** [comment]
Don't know why that didn't work before but I'm sure I must have something wrong. Thanks again!

**Comment by siegelaaron94** [comment]
No problem.
