### ISSUE TITLE
Nothing appears

### ISSUE THREAD

**Issue by GuillaumeDesforges** [siegelaaron94/atom-build-cmake#37]
Hi, I installed on Atom 1.17.2

The plugin is successfully installed (it is shown in Packages) but there is no target shown at the bottom left.

**Comment by BenjaminNavarro** [comment]
Have you opened a project containing a CMakeLists.txt file? It seems to me that the plugin is activated only when it is the case.

**Comment by GuillaumeDesforges** [comment]
Yup, File > Add Project Folder

and I have the CMakeLists.txt, my `cmake -Bbuild && cmake --build build` works just fine.

**Comment by BenjaminNavarro** [comment]
Are the cmake commands available though the [command palette](https://atom.io/packages/command-palette)? (e.g Cmake: all)

From the plugin [source code](https://github.com/siegelaaron94/atom-build-cmake/blob/master/lib/cmake-build-provider.js#L162-L166), I confirm that it should be activated whenever a CMakeLists.txt or CMakeCache.txt is present.

**Comment by GuillaumeDesforges** [comment]
Ah ! No cmake is showing up in command palette. Tho it is written "installed" in package list.

**Comment by BenjaminNavarro** [comment]
So it means that the plugin is not activated and it's not problem with the UI. Could you link your project so that I can test with my installation?

**Comment by GuillaumeDesforges** [comment]
[test.zip](https://github.com/siegelaaron94/atom-build-cmake/files/1356592/test.zip)

Sure ! Thx for helping me

**Comment by BenjaminNavarro** [comment]
It works for me, be sure to have a file from this project (e.g. CMakeLists.txt) opened otherwise Atom might still considers another project to be the active one. One way to be sure is to use File > Open folder instead.

**Comment by siegelaaron94** [comment]
Check out issue #34, I thought I had fixed this though. I will publish a patch in a few minutes. BenjaminNavarro thanks for helping.
