### ISSUE TITLE
Listing warning and errors

### ISSUE THREAD

**Issue by janosimas** [siegelaaron94/atom-build-cmake#5]
Would it be possible to create a table or list with compilation warning and errors?

**Comment by siegelaaron94** [comment]
Upgrade atom-build to version 0.58.0 this feature for errors was just added, you will also need to install [atom-linter](https://atom.io/packages/linter). Beware this version of atom-build seams to have an bug that I have reported [#374](https://github.com/noseglid/atom-build/issues/374) to them as well as a very hacky fix for the bug. As for warnings that will have to be added in atom-build as well.

**Comment by siegelaaron94** [comment]
This bug was fixed in this [commit](https://github.com/noseglid/atom-build/commit/4de59ad14dee44f8f9041d71456b46238250bf0e) but I think it has not been published yet.
